import "./globals.css";
import type { Metadata } from "next";
import LogoutButton from "./components/Auth/LogoutButton";

export const metadata: Metadata = {
  title: "Customer admin webapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LogoutButton />
        {children}
      </body>
    </html>
  );
}
