import "./globals.css";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";

const inter = Urbanist({ subsets: ["latin"], weight: ["500", "600"] });

export const metadata: Metadata = {
  title: "Customer admin webapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
